nelmio_api_doc:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix: /api/doc

duration_controller:
    resource: "@AppBundle/Controller/Api"
    type: rest
    prefix: /api/duration

app:
    resource: '@AppBundle/Controller/'
    type: annotation